spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service:
  greeting: "Hello"
  default-value: "World"